app:
  name: 'teswir-go'
  version: '0.0.1'

http:
  port: '8081'

logger:
  log_level: 'debug'
  rollbar_env: 'teswir-go'

postgres:
  pool_max: 20

auth:
  url: '127.0.0.1:8888'

mongo:
  url: 'mongodb://localhost:27017/'
  database: 'teswir'
  collection: 'users'
